[package]
name = "dont-procede"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.16"
winit = "0.28"
log = "0.4"
env_logger = "0.10"
pollster = "0.3"
